### ISSUE TITLE
Simplify instructions

### ISSUE THREAD

**Issue by jrhorn424** [ga-wdi-boston/js-template-installation#4]
Do this instead of delete history:

<img width="1046" alt="ga-wdi-boston_js-template" src="https://cloud.githubusercontent.com/assets/388761/12685110/5f6a1204-c690-11e5-9e1b-2320019afe8a.png">

<img width="643" alt="slack" src="https://cloud.githubusercontent.com/assets/388761/12685119/73c859cc-c690-11e5-9c55-fdeb1155e2ff.png">

**Comment by J-Weeks** [comment]
instructions updated.
